package com.surveyplatform.repository;

import com.surveyplatform.model.ResultReport;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.List;

// Repository for ResultReport entity managing generated survey analysis reports
@Repository
public interface ResultReportRepository extends JpaRepository<ResultReport, Long> {

    // Find all reports for a specific survey
    List<ResultReport> findBySurveyId(Long surveyId);

    // Find all reports generated by a specific user
    List<ResultReport> findByGeneratedById(Long userId);
}
